apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deploy
  labels:
    app: project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
      - name: project-container
        image: chandini111/health:1.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: project-np-service
  labels:
    app: project-app
spec:
  selector:
    app: project-app

  type: NodePort
  ports:
  - nodePort: 32150  
    port: 8082
    targetPort: 8082
